{% set version = "4.0.0" %}

package:
  name: jupyter_bokeh
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/j/jupyter_bokeh/jupyter_bokeh-{{ version }}-py3-none-any.whl
  sha256: fb7b5ce07869e6dfcdc1d88a7f19760ca080a2c1c936985923466658fb49d183

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed jupyter_bokeh-{{ version }}-py3-none-any.whl

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.9
  run:
    - bokeh 3.*
    - ipywidgets 8.*
    - python >=3.9
  run_constrained:
    - jupyterlab 4.*

test:
  imports:
    - jupyter_bokeh
    - jupyter_bokeh.nbextension
    - jupyter_bokeh.widgets
  commands:
    - pip check
    - jupyter nbextension list
    - jupyter nbextension list 1>nbextensions 2>&1
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "jupyter_bokeh/extension.*enabled" nbextensions
    - grep -iE "@bokeh/jupyter_bokeh.*OK.*jupyter_bokeh" labextensions
  requires:
    - pip
    - jupyterlab
    - m2-grep  # [win]

about:
  home: https://pypi.org/project/jupyter-bokeh
  summary: A Jupyter extension for rendering Bokeh content.
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - jupyter_bokeh/labextension/static/third-party-licenses.json
  dev_url: https://github.com/bokeh/jupyter_bokeh

extra:
  recipe-maintainers:
    - bollwyvl
    - philippjfr
    - mattpap
