{% set version = "4.0.4" %}

package:
  name: jupyter_bokeh
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_bokeh/jupyter_bokeh-{{ version }}.tar.gz
  sha256: f70b70b55c2e53b7d34bf6a244d489dd6b7824d0318790181463f481cc2cd1f8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-jupyter-builder >=0.8.2
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - pip
    - python >=3.9
  run:
    - bokeh 3.*
    - ipywidgets 8.*
    - python >=3.9
  run_constrained:
    - jupyterlab 4.*

test:
  imports:
    - jupyter_bokeh
    - jupyter_bokeh.widgets
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@bokeh/jupyter_bokeh.*OK.*jupyter_bokeh" labextensions
  requires:
    - pip
    - jupyterlab
    - m2-grep  # [win]

about:
  home: https://pypi.org/project/jupyter-bokeh
  summary: A Jupyter extension for rendering Bokeh content.
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - jupyter_bokeh/labextension/static/third-party-licenses.json
  dev_url: https://github.com/bokeh/jupyter_bokeh

extra:
  recipe-maintainers:
    - bollwyvl
    - philippjfr
    - mattpap
